language: node_js

node_js:
  - "16"
  - "14"
  - "12"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - yarn global add codecov

script:
  - npm run lint
  - npm run test -- --coverage && codecov

notifications:
  email:
    on_success: never
